podTemplate(containers: [
    containerTemplate(
        name: 'jenkinsjnlp', 
        image: 'ronniehuang/jenkinsjnlpwithdocker', 
        alwaysPullImage: true 
    ),
  ],
  volumes: [
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
    hostPathVolume(mountPath: '/usr/bin/docker', hostPath: '/usr/bin/docker'),
    hostPathVolume(mountPath: '/usr/local/jdk', hostPath: '/usr/local/jdk'),
    hostPathVolume(mountPath: '/usr/local/maven', hostPath: '/usr/local/maven'),
  ],
  imagePullSecrets: ['registry-pull-secret'],
) 
{
  node(POD_LABEL){
      stage('Git Checkout'){
         checkout scm
      }
      stage('Unit Testing'){
      	echo "Unit Testing..."
      }
      stage('Deploy to K8S'){
          kubernetesDeploy configs: 'deploy/deploy.yaml', kubeConfig: [path: ''], kubeconfigId: 'kube_config_text', secretName: '', ssh: [sshCredentialsId: '*', sshServer: ''], textCredentials: [certificateAuthorityData: '', clientCertificateData: '', clientKeyData: '', serverUrl: 'https://']
      }
      stage('Testing'){
          echo "Testing..."
      }
  }
}

